### PR TITLE
Other pages

### PR DESCRIPTION
**Pull request by gracekabaghe**
styless.css is in this branch

### CODE REVIEW

**Review by Leon-Mbegera — CHANGES_REQUESTED** [review]
Hi @gracekabaghe , 

Good job so far! 🌤
There are some issues that you still need to work on to go to the next project but you are almost there!

**To Highlight**
- A very professional readme file 🌟

## Required Changes ♻️

- [ ] Please change your folder from `.github/workflows` to `github\workflows` instead. The backslash instead of forward slash ensures its only one folder containing your linters file. And ensure that your linter checks pass before re-submitting for re-review. 


## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏
- Please address the above requested change, and then re-submit for another review

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by gracekabaghe** [comment]
Hi  @Leon-Mbegera,
Thanks for the feedback, I've been trying to find a way to change the forward slash to backslash as you suggested but so far, I can't find how to do that. Are you able to point me in the right direction? Thanks.

**Comment by Leon-Mbegera** [comment]
@gracekabaghe 
- You first need to open the repository containing your project on vs code. Then on vs code specifically, create the .github\workflows folder.  This is when you'll use the backslash. 
- Don't create this folder while you're in file explorer or if your project is on your desktop. This is what is making it result in the forward-slash that is making the workflows folder look like a subfolder inside of .github.

**Comment by Leon-Mbegera** [comment]
hi, @gracekabaghe,
just a reminder, On the review, I also noticed the `.gitignore`  file in your other-pages branch is conflicting with the one on your main branch. There is an empty newline at the start of the .gitignore file that is in your other-pages branch. Remove the empty line so that they can both be similar for easy mergeability.

**Pull request merged**
